fix(mysql): catch PyMySQL OperationalError exception (#7919)
## Description of changes

When trying to connect to a mySQL backend, the following error can
appear:

```
OperationalError: (pymysql.err.OperationalError) (1298, "Unknown or incorrect time zone: 'UTC'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

This is due to an exception generated by PyMySQL.
The exception, formerly generated by SQLAlchemy was already caught by
Ibis since #6010, this PR adds a catching of the PyMySQL exception.

## Issues closed
Resolves #7918